#!/bin/sh

if [ "$1" = "clean" ]
then
    rm *.bin
    exit
fi

for i in $(seq 25)
do
    day_on=false
    for j in 1 2
    do
        if [ -f "${i}_${j}.c" ]
        then
            day_on=true
        fi
    done

    if [ "$day_on" != true ]
    then
        continue
    fi

    tput bold
    printf "Day: $i\n"
    tput sgr 0

    in="$i.in"

    if ! [ -f "$in" ]
    then
        printf "Input file not existing."
        continue
    fi

    for j in $(seq 2)
    do
        pref="${i}_${j}"
        src="$pref.c"
        bin="$pref.bin"
        if [ -f "$src" ]
        then
            cc "$src" -o "$bin"
        fi
        if [ -f "$bin" ]
        then
            printf "\tPart $j: "
            tput setaf 3
            cat "./$in" | "./${bin}"
            tput sgr 0
            printf "\n"
        fi
    done
done

